# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name=b'Views Count'),
        ),
    ]
